/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package apresentacao;


//import entidade.Usuario;

import entidade.Motorista;
import entidade.Veiculo;
import java.sql.SQLException;
import java.util.ArrayList;
import javax.swing.JDesktopPane;
import javax.swing.JOptionPane;
import negocio.NMotorista;
import negocio.NVeiculo;
import util.Validation;
import util.fabricaabstrata.CategoriaAbstrata;
import util.interfaces.ComboBox;
//import negocio.UsuarioSisBR;

/**
 *
 * @author aluno
 */
public class FrmCadastroMotorista extends javax.swing.JInternalFrame implements ComboBox{
    private JDesktopPane principal;
    
    
    
    private void limpar(){
        txtCodigoMotorista.setText("");
        txtNome.setText("");
        txtCpf.setText("");
        cmbCategoria.setSelectedIndex(0);
        cmbCategoria.setEnabled(true);
        lblAvisoNome.setText("");
        lblAvisoCpf.setText("");
    }
    
    /**
     * Creates new form frmCadastroFuncionario
     */
    public FrmCadastroMotorista() {
        initComponents();
        limpar();
    }
    
    public FrmCadastroMotorista(JDesktopPane principal){
        this();
        this.principal = principal;
        popularCombo();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jComboBox1 = new javax.swing.JComboBox<>();
        jPasswordField1 = new javax.swing.JPasswordField();
        jLabel9 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        txtCodigoMotorista = new javax.swing.JTextField();
        txtNome = new javax.swing.JTextField();
        txtCpf = new javax.swing.JTextField();
        cmbCategoria = new javax.swing.JComboBox<>();
        jLabel7 = new javax.swing.JLabel();
        btnCadastrar = new javax.swing.JButton();
        btnLimpar = new javax.swing.JButton();
        btnFechar = new javax.swing.JButton();
        btnExcluir = new javax.swing.JButton();
        btnPesquisar = new javax.swing.JButton();
        lblAvisoNome = new javax.swing.JLabel();
        lblAvisoCpf = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        txtCodigoVeiculo = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        txtPlaca = new javax.swing.JTextField();
        txtCor = new javax.swing.JTextField();
        txtModelo = new javax.swing.JTextField();
        btnConsultarVeiculo = new javax.swing.JButton();
        lblAvisoPlaca = new javax.swing.JLabel();
        lblAvisoCor = new javax.swing.JLabel();
        lblAvisoModelo = new javax.swing.JLabel();

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jPasswordField1.setText("jPasswordField1");

        jLabel9.setText("jLabel9");

        setTitle("Cadastro de Motorista");

        jLabel1.setText("Código Motorista:");

        jLabel2.setText("Nome:");

        jLabel4.setText("CPF:");

        txtCodigoMotorista.setEditable(false);

        txtNome.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtNomeKeyPressed(evt);
            }
        });

        txtCpf.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtCpfKeyTyped(evt);
            }
        });

        cmbCategoria.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Categoria" }));
        cmbCategoria.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbCategoriaActionPerformed(evt);
            }
        });

        jLabel7.setText("Categoria Veículo:");

        btnCadastrar.setText("Cadastrar");
        btnCadastrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCadastrarActionPerformed(evt);
            }
        });

        btnLimpar.setText("Limpar");
        btnLimpar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLimparActionPerformed(evt);
            }
        });

        btnFechar.setText("Fechar");
        btnFechar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFecharActionPerformed(evt);
            }
        });

        btnExcluir.setText("Excluir");
        btnExcluir.setEnabled(false);
        btnExcluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExcluirActionPerformed(evt);
            }
        });

        btnPesquisar.setText("Pesquisar");
        btnPesquisar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPesquisarActionPerformed(evt);
            }
        });

        lblAvisoNome.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        lblAvisoNome.setText("Aviso Nome");

        lblAvisoCpf.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        lblAvisoCpf.setText("Aviso CPF");

        jLabel5.setText("Código Veículo:");

        jLabel3.setText("Placa:");

        jLabel6.setText("Cor:");

        jLabel8.setText("Modelo:");

        txtPlaca.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtPlacaKeyPressed(evt);
            }
        });

        txtCor.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtCorKeyPressed(evt);
            }
        });

        txtModelo.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtModeloKeyPressed(evt);
            }
        });

        btnConsultarVeiculo.setText("Consultar Veículos");
        btnConsultarVeiculo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnConsultarVeiculoActionPerformed(evt);
            }
        });

        lblAvisoPlaca.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        lblAvisoPlaca.setText("Aviso Placa");

        lblAvisoCor.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        lblAvisoCor.setText("Aviso Cor");

        lblAvisoModelo.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        lblAvisoModelo.setText("Aviso Modelo");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(182, 182, 182)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(txtCodigoMotorista, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(btnPesquisar)))
                .addGap(63, 63, 63))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(28, 28, 28)
                        .addComponent(btnCadastrar, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(50, 50, 50)
                        .addComponent(btnExcluir, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(50, 50, 50)
                        .addComponent(btnLimpar, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(50, 50, 50)
                        .addComponent(btnFechar, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(65, 65, 65)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel1)
                            .addComponent(jLabel2)
                            .addComponent(jLabel4)
                            .addComponent(jLabel5)
                            .addComponent(jLabel3)
                            .addComponent(jLabel6)
                            .addComponent(jLabel8))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(txtCodigoVeiculo)
                                .addGap(33, 33, 33)
                                .addComponent(jLabel7)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(cmbCategoria, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(4, 4, 4))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(txtModelo, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 112, Short.MAX_VALUE)
                                    .addComponent(txtCor, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtPlaca, javax.swing.GroupLayout.Alignment.LEADING))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(btnConsultarVeiculo)
                                .addGap(46, 46, 46))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtNome, javax.swing.GroupLayout.PREFERRED_SIZE, 242, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                        .addComponent(lblAvisoCpf, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(lblAvisoNome, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 205, Short.MAX_VALUE))
                                    .addComponent(txtCpf, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(lblAvisoPlaca, javax.swing.GroupLayout.PREFERRED_SIZE, 171, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(lblAvisoCor, javax.swing.GroupLayout.PREFERRED_SIZE, 171, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(lblAvisoModelo, javax.swing.GroupLayout.PREFERRED_SIZE, 171, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(0, 0, Short.MAX_VALUE)))))
                .addContainerGap(29, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtCodigoMotorista, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addGap(37, 37, 37)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnPesquisar)
                    .addComponent(jLabel2)
                    .addComponent(txtNome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblAvisoNome, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(21, 21, 21)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(txtCpf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblAvisoCpf, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(21, 21, 21)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(txtCodigoVeiculo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7)
                    .addComponent(cmbCategoria, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(34, 34, 34)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txtPlaca, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnConsultarVeiculo))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblAvisoPlaca, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtCor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6))
                .addGap(10, 10, 10)
                .addComponent(lblAvisoCor, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtModelo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblAvisoModelo, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 44, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnCadastrar)
                    .addComponent(btnExcluir)
                    .addComponent(btnLimpar)
                    .addComponent(btnFechar))
                .addGap(36, 36, 36))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cmbCategoriaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbCategoriaActionPerformed
        
    }//GEN-LAST:event_cmbCategoriaActionPerformed

    private void btnCadastrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCadastrarActionPerformed
        try {
            ArrayList<String> textos = new ArrayList<>();
            String regex = "[\u0020-\u002C|\u002E|\u002F|\u003A-\u0040|\\u005B-\u02AC]";

            textos.removeAll(textos);
            textos.add(txtNome.getText());
            textos.add(txtCpf.getText());
            textos.add(txtPlaca.getText());
            textos.add(txtCor.getText());
            textos.add(txtModelo.getText());

            Validation.isEmpty(textos);
            Validation.invalidSpecCaracters(regex, txtPlaca.getText());
            Validation.invalidCaracAndLetters(txtCpf.getText());
            Validation.invalidCaracAndNumbers(txtNome.getText());
            Validation.invalidSpaces(txtCpf.getText());
            Validation.invalidCpf(txtCpf.getText());

            Veiculo veiculo = new Veiculo();
            Motorista motorista = new Motorista();

            motorista.setNome(txtNome.getText());
            motorista.setCpf(txtCpf.getText());
            motorista.setStatusMotorista(true);
            motorista.setStatusDeCorrida(false);

            veiculo.setCategoria(CategoriaAbstrata.getInstance(cmbCategoria.getSelectedIndex()));
            veiculo.setPlaca(txtPlaca.getText());
            veiculo.setCor(txtCor.getText());
            veiculo.setModelo(txtModelo.getText());

            motorista.setVeiculo(veiculo);

            if(txtCodigoMotorista.getText() != null && !txtCodigoMotorista.getText().isEmpty()){
                motorista.setCodigoTipo(Integer.parseInt(txtCodigoMotorista.getText()));
            }

            if(txtCodigoVeiculo.getText() != null && !txtCodigoVeiculo.getText().isEmpty()){
                veiculo.setCodigoTipo(Integer.parseInt(txtCodigoVeiculo.getText()));
            }
            
            new NVeiculo().incluir(veiculo);
            new NMotorista().incluir(motorista);
            
            limpar();
            JOptionPane.showMessageDialog(rootPane, "Motorista cadastrado com sucesso!");
        } catch (Exception e) {
            JOptionPane.showMessageDialog(rootPane, e.getMessage());
        }
    }//GEN-LAST:event_btnCadastrarActionPerformed

    private void btnFecharActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFecharActionPerformed
        this.dispose();
    }//GEN-LAST:event_btnFecharActionPerformed

    private void btnLimparActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLimparActionPerformed
        limpar();
    }//GEN-LAST:event_btnLimparActionPerformed

    private void btnPesquisarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPesquisarActionPerformed
        try {
            FrmPesquisaGeral janela = new FrmPesquisaGeral(principal, 0);
            principal.add(janela);
            janela.setVisible(true);
            this.dispose();
        } catch (Exception e) {
            JOptionPane.showMessageDialog(rootPane, e.getMessage());
        }
    }//GEN-LAST:event_btnPesquisarActionPerformed

    private void txtNomeKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtNomeKeyPressed
        try {
            Validation.limitMaxCaracter(50, txtNome.getText(), evt);
        } catch (Exception e) {
            lblAvisoNome.setText(e.getMessage());
        }
    }//GEN-LAST:event_txtNomeKeyPressed

    private void txtCpfKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtCpfKeyTyped
        try {
            Validation.limitMaxCaracter(11, txtCpf.getText(), evt);
        } catch (Exception e) {
            lblAvisoCpf.setText(e.getMessage());
        }
    }//GEN-LAST:event_txtCpfKeyTyped

    private void btnExcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExcluirActionPerformed
//        try {
//            int resposta = JOptionPane.showConfirmDialog(null, 
//                    "Confirma a exclusão do \"Funcionário\" ?",
//                    "Gestão Almoxarifado", JOptionPane.YES_NO_OPTION);
//            
//            if(resposta == JOptionPane.YES_OPTION){
//                if(cmbCategoria.getSelectedIndex() == 0)
//                    new UsuarioSisBR().deletar(Integer.parseInt(txtCodigoFunc.getText()));
//                else
//                    new FuncionarioBR().deletar(Integer.parseInt(txtCodigoFunc.getText()));
//                
//                JOptionPane.showMessageDialog(rootPane, 
//                        "Operação efetuada com sucesso!");
//                limpar();
//            }
//        } catch (Exception e) {
//            JOptionPane.showMessageDialog(rootPane, e.getMessage());
//        }
    }//GEN-LAST:event_btnExcluirActionPerformed

    private void txtPlacaKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtPlacaKeyPressed
        try {
            Validation.limitMaxCaracter(8, txtPlaca.getText(), evt);
        } catch (Exception e) {
            lblAvisoPlaca.setText(e.getMessage());
        }
    }//GEN-LAST:event_txtPlacaKeyPressed

    private void txtCorKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtCorKeyPressed
        try {
            Validation.limitMaxCaracter(10, txtCor.getText(), evt);
        } catch (Exception e) {
            lblAvisoCor.setText(e.getMessage());
        }
    }//GEN-LAST:event_txtCorKeyPressed

    private void txtModeloKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtModeloKeyPressed
        try {
            Validation.limitMaxCaracter(25, txtModelo.getText(), evt);
        } catch (Exception e) {
            lblAvisoModelo.setText(e.getMessage());
        }
    }//GEN-LAST:event_txtModeloKeyPressed

    private void btnConsultarVeiculoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnConsultarVeiculoActionPerformed
        try {
            FrmPesquisaGeral janela = new FrmPesquisaGeral(principal, 3);
            principal.add(janela);
            janela.setVisible(true);
        } catch (Exception e) {
            JOptionPane.showMessageDialog(rootPane, e.getMessage());
        }
    }//GEN-LAST:event_btnConsultarVeiculoActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCadastrar;
    private javax.swing.JButton btnConsultarVeiculo;
    private javax.swing.JButton btnExcluir;
    private javax.swing.JButton btnFechar;
    private javax.swing.JButton btnLimpar;
    private javax.swing.JButton btnPesquisar;
    private javax.swing.JComboBox<String> cmbCategoria;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPasswordField jPasswordField1;
    private javax.swing.JLabel lblAvisoCor;
    private javax.swing.JLabel lblAvisoCpf;
    private javax.swing.JLabel lblAvisoModelo;
    private javax.swing.JLabel lblAvisoNome;
    private javax.swing.JLabel lblAvisoPlaca;
    private javax.swing.JTextField txtCodigoMotorista;
    private javax.swing.JTextField txtCodigoVeiculo;
    private javax.swing.JTextField txtCor;
    private javax.swing.JTextField txtCpf;
    private javax.swing.JTextField txtModelo;
    private javax.swing.JTextField txtNome;
    private javax.swing.JTextField txtPlaca;
    // End of variables declaration//GEN-END:variables

    @Override
    public void popularCombo() {
        try {
            cmbCategoria.removeAllItems();
            CategoriaAbstrata.getListaDeCategorias().forEachRemaining(categoria ->{
                cmbCategoria.addItem(categoria.getDescricao());
            });
        } catch (SQLException ex) {
            ex.printStackTrace();
//            JOptionPane.showMessageDialog(null, ex.getMessage());
        }
    }

//    private void preencherTelaAlmox(Funcionario func) {
//        try {
//            txtCodigoFunc.setText(func.getId()+"");
//            txtMatricula.setText(func.getMatricula());
//            txtNome.setText(func.getNome());
//            
//            btnExcluir.setEnabled(true);
//        } catch (Exception e) {
//            JOptionPane.showMessageDialog(rootPane, e.getMessage());
//        }
//    }
//
//    private void preencherTelaSis(Usuario usuario) {
//        try {
//            txtCodigoFunc.setText(usuario.getFuncionario().getId()+"");
//            txtCodUsuario.setText(usuario.getIdUsuario()+"");
//            txtMatricula.setText(usuario.getFuncionario().getMatricula());
//            txtNome.setText(usuario.getFuncionario().getNome());
//            txtCpf.setText(usuario.getCpf()+"");
//            txtEmail.setText(usuario.getEmail());
//            txtSenha.setText(usuario.getSenha());
//            
//            btnExcluir.setEnabled(true);
//        } catch (Exception e) {
//            JOptionPane.showMessageDialog(rootPane, e.getMessage());
//        }
//    }

    
}
