/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package apresentacao;



import entidade.Solicitacao;
import java.text.DateFormat;
import java.text.DecimalFormat;
import java.text.SimpleDateFormat;
import java.time.LocalDate;
import java.util.ArrayList;
import java.util.Date;
import java.util.Vector;
import javax.swing.JDesktopPane;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import util.Validation;

/**
 *
 * @author Kleiton
 */
public class FrmRegistroViagem extends javax.swing.JInternalFrame{
    private JDesktopPane principal;

    /**
     * Creates new form frmTipoAssociadoCadoastr
     */
    public FrmRegistroViagem() {
        initComponents();
    }
    
    public FrmRegistroViagem(JDesktopPane principal){
        this();
        this.principal = principal;
    }
    
    public FrmRegistroViagem(JDesktopPane principal, Solicitacao inscricao){
        this();
        this.principal = principal;
    }


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane3 = new javax.swing.JScrollPane();
        jEditorPane1 = new javax.swing.JEditorPane();
        jLabel1 = new javax.swing.JLabel();
        txtCodigoInscricao = new javax.swing.JTextField();
        btnPesquisarInsc = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblJogador = new javax.swing.JTable();
        jLabel3 = new javax.swing.JLabel();
        txtJogador = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        txtCodJogador = new javax.swing.JTextField();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblTorneio = new javax.swing.JTable();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel5 = new javax.swing.JLabel();
        txtCodTorneio = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        txtDescricaoTorn = new javax.swing.JTextField();
        rdSalvar = new javax.swing.JRadioButton();
        rdExcluir = new javax.swing.JRadioButton();
        rdLimparCanc = new javax.swing.JRadioButton();
        btnConfirmar = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        txtCodCatJogador = new javax.swing.JTextField();
        txtCpf = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        txtCodCatTorneio = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        txtDataInicio = new javax.swing.JTextField();
        txtDataTermino = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        txtTaxa = new javax.swing.JTextField();
        btnNotificar = new javax.swing.JButton();

        jScrollPane3.setViewportView(jEditorPane1);

        setClosable(true);
        setTitle("Registro de Viagens");

        jLabel1.setText("Identificador");

        txtCodigoInscricao.setEditable(false);

        btnPesquisarInsc.setText("Pesquisar Registros");
        btnPesquisarInsc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPesquisarInscActionPerformed(evt);
            }
        });

        tblJogador.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        tblJogador.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                tblJogadorMousePressed(evt);
            }
        });
        jScrollPane1.setViewportView(tblJogador);

        jLabel3.setText("Nome:");

        txtJogador.setEditable(false);

        jLabel4.setText("Código Motorista:");

        txtCodJogador.setEditable(false);

        tblTorneio.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        tblTorneio.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                tblTorneioMousePressed(evt);
            }
        });
        jScrollPane2.setViewportView(tblTorneio);

        jLabel5.setText("Identificador do Torneio");

        txtCodTorneio.setEditable(false);

        jLabel6.setText("Torneio");

        txtDescricaoTorn.setEditable(false);

        rdSalvar.setText("Registrar");
        rdSalvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rdSalvarActionPerformed(evt);
            }
        });

        rdExcluir.setText("Excluir");
        rdExcluir.setEnabled(false);
        rdExcluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rdExcluirActionPerformed(evt);
            }
        });

        rdLimparCanc.setText("Limpar / Cancelar");
        rdLimparCanc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rdLimparCancActionPerformed(evt);
            }
        });

        btnConfirmar.setText("Confirmar ação");
        btnConfirmar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnConfirmarActionPerformed(evt);
            }
        });

        jLabel7.setText("Código Categoria");

        jLabel8.setText("CPF");

        txtCodCatJogador.setEditable(false);

        txtCpf.setEditable(false);

        jLabel9.setText("Código Categoria");

        txtCodCatTorneio.setEditable(false);

        jLabel10.setText("Data início");

        jLabel11.setText("Data término");

        txtDataInicio.setEditable(false);

        txtDataTermino.setEditable(false);

        jLabel12.setText("Taxa");

        txtTaxa.setEditable(false);

        btnNotificar.setText("Notificar Passageiros");
        btnNotificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNotificarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSeparator1)
            .addGroup(layout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(txtCodigoInscricao, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 187, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(rdSalvar)
                    .addComponent(rdExcluir))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(21, 21, 21)
                        .addComponent(btnConfirmar))
                    .addComponent(rdLimparCanc))
                .addGap(121, 121, 121)
                .addComponent(btnPesquisarInsc)
                .addGap(43, 43, 43))
            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING)
            .addComponent(jScrollPane2)
            .addGroup(layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel6)
                    .addComponent(jLabel5))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtDescricaoTorn, javax.swing.GroupLayout.PREFERRED_SIZE, 263, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(txtCodTorneio, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(30, 30, 30)
                        .addComponent(jLabel9)
                        .addGap(18, 18, 18)
                        .addComponent(txtCodCatTorneio, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(25, 25, 25)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel11)
                    .addComponent(jLabel10))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(txtDataInicio, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(35, 35, 35)
                        .addComponent(jLabel12)
                        .addGap(18, 18, 18)
                        .addComponent(txtTaxa, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(txtDataTermino, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel3)
                    .addComponent(jLabel4))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(txtJogador, javax.swing.GroupLayout.PREFERRED_SIZE, 206, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel8))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(txtCodJogador, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(156, 156, 156)
                        .addComponent(jLabel7)))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtCodCatJogador, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtCpf, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnNotificar)
                .addGap(68, 68, 68))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(9, 9, 9)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(txtCodigoInscricao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(rdSalvar)
                            .addComponent(rdLimparCanc))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(rdExcluir)
                            .addComponent(btnConfirmar)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(23, 23, 23)
                        .addComponent(btnPesquisarInsc)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtCodJogador, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4)
                            .addComponent(jLabel7)
                            .addComponent(txtCodCatJogador, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLabel3)
                                .addComponent(txtJogador, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLabel8)
                                .addComponent(txtCpf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(28, 28, 28)
                        .addComponent(btnNotificar)))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 243, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(txtCodTorneio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel9)
                    .addComponent(txtCodCatTorneio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel10)
                    .addComponent(txtDataInicio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel12)
                    .addComponent(txtTaxa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(txtDescricaoTorn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel11)
                    .addComponent(txtDataTermino, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 255, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void rdSalvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rdSalvarActionPerformed
        rdSalvar.setSelected(true);
        rdExcluir.setSelected(false);
        rdLimparCanc.setSelected(false);
    }//GEN-LAST:event_rdSalvarActionPerformed

    private void rdExcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rdExcluirActionPerformed
        rdSalvar.setSelected(false);
        rdExcluir.setSelected(true);
        rdLimparCanc.setSelected(false);
    }//GEN-LAST:event_rdExcluirActionPerformed

    private void rdLimparCancActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rdLimparCancActionPerformed
        rdSalvar.setSelected(false);
        rdExcluir.setSelected(false);
        rdLimparCanc.setSelected(true);
    }//GEN-LAST:event_rdLimparCancActionPerformed

    private void btnConfirmarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnConfirmarActionPerformed
        try {
            if(rdSalvar.isSelected()){
            } else if (rdExcluir.isSelected()){
            } else limparTela();
        } catch (Exception e) {
            e.printStackTrace();
            JOptionPane.showMessageDialog(rootPane, e.getMessage());
        }
    }//GEN-LAST:event_btnConfirmarActionPerformed

    private void tblJogadorMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblJogadorMousePressed
        int linha = tblJogador.getSelectedRow();
        
        txtCodJogador.setText(tblJogador.getValueAt(linha,0).toString());
        txtJogador.setText(tblJogador.getValueAt(linha,1).toString());
        txtCodCatJogador.setText(tblJogador.getValueAt(linha,2).toString());
        txtCpf.setText(tblJogador.getValueAt(linha,3).toString());
    }//GEN-LAST:event_tblJogadorMousePressed

    private void tblTorneioMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblTorneioMousePressed
        
        int linha = tblTorneio.getSelectedRow();
        txtCodTorneio.setText(tblTorneio.getValueAt(linha, 0).toString());
        txtDescricaoTorn.setText(tblTorneio.getValueAt(linha, 1).toString());
        txtCodCatTorneio.setText(tblTorneio.getValueAt(linha, 2).toString());
        txtDataInicio.setText(tblTorneio.getValueAt(linha, 3).toString());
        txtDataTermino.setText(tblTorneio.getValueAt(linha, 4).toString());
        txtTaxa.setText(tblTorneio.getValueAt(linha, 5).toString());
    }//GEN-LAST:event_tblTorneioMousePressed

    private void btnNotificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNotificarActionPerformed
        atualizar();
    }//GEN-LAST:event_btnNotificarActionPerformed

    private void btnPesquisarInscActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPesquisarInscActionPerformed
        try {
            FrmPesquisaGeral janela = new FrmPesquisaGeral(principal, 2);
            principal.add(janela);
            janela.setVisible(true);
            this.dispose();
        } catch (Exception e) {
//            e.printStackTrace();
            JOptionPane.showMessageDialog(rootPane, e.getMessage());
        }
    }//GEN-LAST:event_btnPesquisarInscActionPerformed

    private void limparTela(){
        rdExcluir.setEnabled(false);
        txtCodigoInscricao.setText("");
        rdSalvar.setSelected(false);
        rdExcluir.setSelected(false);
        rdLimparCanc.setSelected(false);
        txtCodJogador.setText("");
        txtJogador.setText("");
        txtCodCatJogador.setText("");
        txtCpf.setText("");
        txtCodTorneio.setText("");
        txtCodCatTorneio.setText("");
        txtDescricaoTorn.setText("");
        txtDataInicio.setText("");
        txtDataTermino.setText("");
        txtTaxa.setText(title);
    }
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnConfirmar;
    private javax.swing.JButton btnNotificar;
    private javax.swing.JButton btnPesquisarInsc;
    private javax.swing.JEditorPane jEditorPane1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JRadioButton rdExcluir;
    private javax.swing.JRadioButton rdLimparCanc;
    private javax.swing.JRadioButton rdSalvar;
    private javax.swing.JTable tblJogador;
    private javax.swing.JTable tblTorneio;
    private javax.swing.JTextField txtCodCatJogador;
    private javax.swing.JTextField txtCodCatTorneio;
    private javax.swing.JTextField txtCodJogador;
    private javax.swing.JTextField txtCodTorneio;
    private javax.swing.JTextField txtCodigoInscricao;
    private javax.swing.JTextField txtCpf;
    private javax.swing.JTextField txtDataInicio;
    private javax.swing.JTextField txtDataTermino;
    private javax.swing.JTextField txtDescricaoTorn;
    private javax.swing.JTextField txtJogador;
    private javax.swing.JTextField txtTaxa;
    // End of variables declaration//GEN-END:variables

    

    private void preencherTabela(int index){
        try {
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e.getMessage());
        }
        
    }
    
   
    
    private Vector<String> tabelaMotorista(){
            Vector<String> cabecalho = new Vector<>();
            cabecalho.add("Código");
            cabecalho.add("Nome");
            cabecalho.add("Categoria");
            cabecalho.add("CPF");
            
            return cabecalho;
    }
    
    private Vector<String> tabelaPassageiro(){
        Vector<String> cabecalho = new Vector<>();
        cabecalho.add("Código");
        cabecalho.add("Descrição");
        cabecalho.add("Categoria");
        cabecalho.add("Data Início");
        cabecalho.add("Data Término");
        cabecalho.add("Taxa");

        return cabecalho;
    }
    
    private void atualizar(){
        try {
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e.getMessage());
        }
    }
    
    private ArrayList<String> validarCampos(){
        ArrayList<String> lista = new ArrayList<>();
        
        lista.add(txtCodJogador.getText());
        lista.add(txtJogador.getText());
        lista.add(txtCodCatJogador.getText());
        lista.add(txtCpf.getText());
        lista.add(txtCodTorneio.getText());
        lista.add(txtDescricaoTorn.getText());
        lista.add(txtCodCatTorneio.getText());
        lista.add(txtDataInicio.getText());
        lista.add(txtDataTermino.getText());
        lista.add(txtTaxa.getText());
        
        return lista;
    }
}
